# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ZaraUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ZaraUi(object):
    def setupUi(self, ZaraUi):
        ZaraUi.setObjectName("ZaraUi")
        ZaraUi.resize(1884, 867)
        self.centralwidget = QtWidgets.QWidget(ZaraUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1911, 871))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(0, 170, 255)")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/background_img.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1670, 790, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(0, 85, 255)")
        self.pushButton.setAutoDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1770, 790, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("\n"
"background-color:rgb(255, 0, 0)")
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 0, 481, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/top_loading.gif"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1220, 10, 321, 51))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:None;\n color:white;\n font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1550, 10, 321, 51))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:None;\n color:white;\n font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        ZaraUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(ZaraUi)
        QtCore.QMetaObject.connectSlotsByName(ZaraUi)

    def retranslateUi(self, ZaraUi):
        _translate = QtCore.QCoreApplication.translate
        ZaraUi.setWindowTitle(_translate("ZaraUi", "MainWindow"))
        self.pushButton.setText(_translate("ZaraUi", "Run"))
        self.pushButton_2.setText(_translate("ZaraUi", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ZaraUi = QtWidgets.QMainWindow()
    ui = Ui_ZaraUi()
    ui.setupUi(ZaraUi)
    ZaraUi.show()
    sys.exit(app.exec_())
